import Head from 'next/head'
import { connect } from 'react-redux'
import styles from '../styles/Home.module.css'

const Home = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Utility App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Utility!
        </h1>
       </main>
    </div>
  )
}

export default connect()(Home)